#pragma once

#include "../Maths/AABB.hpp"
#include "../Maths/Colour.hpp"
#include "../Maths/Degree.hpp"
#include "../Maths/Frustrum.hpp"
#include "../Maths/Math.hpp"
#include "../Maths/Matrix3.hpp"
#include "../Maths/Matrix4.hpp"
#include "../Maths/Quaternion.hpp"
#include "../Maths/Radian.hpp"
#include "../Maths/Vector2.hpp"
#include "../Maths/Vector3.hpp"
#include "../Maths/Vector4.hpp"
#include "../Maths/Vector2I.hpp"